default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username : root
  password : root
  database: db_name

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default